

INSERT INTO ARTIST (ARTIST_NAME, ARTIST_YEAR)
VALUES ('Don Omar', 2002);
INSERT INTO ARTIST (ARTIST_NAME, ARTIST_YEAR)
VALUES ('Olga Tañon', 2003);
INSERT INTO ARTIST (ARTIST_NAME, ARTIST_YEAR)
VALUES ('Alejandro Fernandez', 1998);

INSERT INTO STYLE (STYLE_NAME)
VALUES ('Urbano');
INSERT INTO STYLE (STYLE_NAME)
VALUES ('Tropical');
INSERT INTO STYLE (STYLE_NAME)
VALUES ('Rancheras');
INSERT INTO STYLE (STYLE_NAME)
VALUES ('Pop');
INSERT INTO STYLE (STYLE_NAME)
VALUES ('Hip Hop');
INSERT INTO STYLE (STYLE_NAME)
VALUES ('Latino');
INSERT INTO STYLE (STYLE_NAME)
VALUES ('Jazz');
INSERT INTO STYLE (STYLE_NAME)
VALUES ('Alternativo');

INSERT INTO PEOPLE (PEOPLE_NAME, PEOPLE_YEARS, ARTIST_ID)
VALUES ('Alejandro', 30 , 1);
INSERT INTO PEOPLE (PEOPLE_NAME, PEOPLE_YEARS, ARTIST_ID)
VALUES ('Carlos', 22 , 1);
INSERT INTO PEOPLE (PEOPLE_NAME, PEOPLE_YEARS, ARTIST_ID)
VALUES ('Juan', 22 , null);
INSERT INTO PEOPLE (PEOPLE_NAME, PEOPLE_YEARS, ARTIST_ID)
VALUES ('Maria', 22 , null);

INSERT INTO ARTIST_RELATED (ARTIST_ID, ARTIST_RELATED_ID)
VALUES (1,2);
INSERT INTO ARTIST_RELATED (ARTIST_ID, ARTIST_RELATED_ID)
VALUES (1,3);
INSERT INTO ARTIST_RELATED (ARTIST_ID, ARTIST_RELATED_ID)
VALUES (2,1);

INSERT INTO ARTIST_STYLE (ARTIST_ID, STYLE_ID)
VALUES (1,1);
INSERT INTO ARTIST_STYLE (ARTIST_ID, STYLE_ID)
VALUES (1,2);
INSERT INTO ARTIST_STYLE (ARTIST_ID, STYLE_ID)
VALUES (2,1);
INSERT INTO ARTIST_STYLE (ARTIST_ID, STYLE_ID)
VALUES (3,1);
INSERT INTO ARTIST_STYLE (ARTIST_ID, STYLE_ID)
VALUES (3,5);